import 'ingredient.dart';
import 'recipe.dart';
import 'learn_card.dart';

final mockIngredients = [
  Ingredient(
    id: '1',
    name: '달걀',
    category: IngredientCategory.dairy,
    quantity: 6,
    unit: '개',
    expiryDate: DateTime.now().add(const Duration(days: 2)),
    emoji: '🥚',
  ),
  Ingredient(
    id: '2',
    name: '대파',
    category: IngredientCategory.vegetable,
    quantity: 1,
    unit: '단',
    expiryDate: DateTime.now().add(const Duration(days: 1)),
    emoji: '🧅',
  ),
  Ingredient(
    id: '3',
    name: '돼지고기 앞다리살',
    category: IngredientCategory.meat,
    quantity: 300,
    unit: 'g',
    expiryDate: DateTime.now().add(const Duration(days: 3)),
    emoji: '🥩',
  ),
  Ingredient(
    id: '4',
    name: '두부',
    category: IngredientCategory.dairy,
    quantity: 1,
    unit: '모',
    expiryDate: DateTime.now().subtract(const Duration(days: 1)),
    emoji: '🫙',
  ),
  Ingredient(
    id: '5',
    name: '당근',
    category: IngredientCategory.vegetable,
    quantity: 2,
    unit: '개',
    expiryDate: DateTime.now().add(const Duration(days: 10)),
    emoji: '🥕',
  ),
  Ingredient(
    id: '6',
    name: '양파',
    category: IngredientCategory.vegetable,
    quantity: 3,
    unit: '개',
    expiryDate: DateTime.now().add(const Duration(days: 14)),
    emoji: '🧅',
  ),
  Ingredient(
    id: '7',
    name: '밥',
    category: IngredientCategory.grain,
    quantity: 2,
    unit: '공기',
    expiryDate: DateTime.now().add(const Duration(days: 2)),
    emoji: '🍚',
  ),
  Ingredient(
    id: '8',
    name: '간장',
    category: IngredientCategory.seasoning,
    quantity: 200,
    unit: 'ml',
    expiryDate: DateTime.now().add(const Duration(days: 180)),
    emoji: '🫙',
  ),
  Ingredient(
    id: '9',
    name: '참기름',
    category: IngredientCategory.seasoning,
    quantity: 100,
    unit: 'ml',
    expiryDate: DateTime.now().add(const Duration(days: 90)),
    emoji: '🫙',
  ),
  Ingredient(
    id: '10',
    name: '김치',
    category: IngredientCategory.processed,
    quantity: 500,
    unit: 'g',
    expiryDate: DateTime.now().add(const Duration(days: 30)),
    emoji: '🥬',
  ),
];

final mockRecipes = [
  Recipe(
    id: 'r1',
    title: '계란볶음밥',
    description: '냉장고 속 남은 재료로 5분 만에 완성하는 초간단 볶음밥',
    difficulty: 1,
    cookingTimeMinutes: 8,
    servings: 1,
    emoji: '🍳',
    category: '한식',
    tags: ['초간단', '5분요리', '계란', '혼밥'],
    matchRate: 0.95,
    hasUrgentIngredient: true,
    ingredients: [
      const RecipeIngredient(name: '밥', amount: 1, unit: '공기'),
      const RecipeIngredient(name: '달걀', amount: 2, unit: '개'),
      const RecipeIngredient(name: '대파', amount: 0.5, unit: '대'),
      const RecipeIngredient(name: '간장', amount: 1, unit: '큰술'),
      const RecipeIngredient(name: '참기름', amount: 0.5, unit: '큰술'),
      const RecipeIngredient(name: '당근', amount: 0.5, unit: '개', importance: IngredientImportance.optional),
    ],
    steps: [
      const RecipeStep(
        order: 1,
        description: '달걀 2개를 그릇에 풀어 소금 한 꼬집을 넣어 잘 섞어 주세요.',
        tip: '달걀은 미리 실온에 꺼내두면 더 부드럽게 익어요.',
      ),
      const RecipeStep(
        order: 2,
        description: '당근과 대파를 잘게 다져 주세요.',
      ),
      const RecipeStep(
        order: 3,
        description: '달궈진 팬에 식용유를 두르고 달걀물을 넣어 반숙 상태로 스크램블 해주세요.',
        tip: '불을 강불로 켜야 달걀이 팬에 붙지 않아요.',
        duration: Duration(minutes: 1),
      ),
      const RecipeStep(
        order: 4,
        description: '달걀을 팬 한쪽으로 밀어두고, 같은 팬에 당근을 30초 볶아 주세요.',
      ),
      const RecipeStep(
        order: 5,
        description: '밥을 넣고 간장 1큰술을 둘러 센 불에서 볶아 주세요.',
        duration: Duration(minutes: 2),
      ),
      const RecipeStep(
        order: 6,
        description: '불을 끄고 대파와 참기름을 넣어 마무리해 주세요.',
        tip: '참기름은 불을 끈 뒤 넣어야 고소한 향이 살아요.',
      ),
    ],
    nutrition: const Nutrition(
      calories: 480,
      carbs: 65,
      protein: 18,
      fat: 14,
    ),
  ),
  Recipe(
    id: 'r2',
    title: '두부 김치찌개',
    description: '묵은 김치와 두부로 만드는 얼큰 김치찌개. 속 든든한 한 끼!',
    difficulty: 2,
    cookingTimeMinutes: 20,
    servings: 2,
    emoji: '🍲',
    category: '한식',
    tags: ['찌개', '김치', '두부', '얼큰'],
    matchRate: 0.88,
    hasUrgentIngredient: false,
    ingredients: [
      const RecipeIngredient(name: '김치', amount: 200, unit: 'g'),
      const RecipeIngredient(name: '두부', amount: 1, unit: '모'),
      const RecipeIngredient(name: '돼지고기 앞다리살', amount: 100, unit: 'g'),
      const RecipeIngredient(name: '대파', amount: 1, unit: '대'),
      const RecipeIngredient(name: '간장', amount: 1, unit: '큰술'),
      const RecipeIngredient(name: '고춧가루', amount: 1, unit: '큰술'),
      const RecipeIngredient(name: '다진 마늘', amount: 1, unit: '큰술'),
    ],
    steps: [
      const RecipeStep(
        order: 1,
        description: '김치는 먹기 좋은 크기로 썰고, 두부는 깍둑썰기 해주세요.',
      ),
      const RecipeStep(
        order: 2,
        description: '냄비에 참기름을 두르고 돼지고기와 김치를 2분간 볶아 주세요.',
        tip: '김치와 고기를 볶으면 깊은 맛이 나요.',
        duration: Duration(minutes: 2),
      ),
      const RecipeStep(
        order: 3,
        description: '물 400ml를 넣고 고춧가루, 다진 마늘을 추가해 중불로 10분 끓여 주세요.',
        duration: Duration(minutes: 10),
      ),
      const RecipeStep(
        order: 4,
        description: '두부를 넣고 5분 더 끓인 뒤 대파를 올려 마무리해 주세요.',
        duration: Duration(minutes: 5),
      ),
    ],
    nutrition: const Nutrition(
      calories: 320,
      carbs: 12,
      protein: 22,
      fat: 18,
    ),
  ),
  Recipe(
    id: 'r3',
    title: '당근 라페',
    description: '프랑스식 당근 샐러드. 냉장고에서 3일 보관 가능한 든든한 밑반찬',
    difficulty: 1,
    cookingTimeMinutes: 15,
    servings: 4,
    emoji: '🥗',
    category: '양식',
    tags: ['샐러드', '당근', '간단', '밑반찬'],
    matchRate: 0.75,
    hasUrgentIngredient: false,
    ingredients: [
      const RecipeIngredient(name: '당근', amount: 2, unit: '개'),
      const RecipeIngredient(name: '식초', amount: 2, unit: '큰술'),
      const RecipeIngredient(name: '올리브유', amount: 2, unit: '큰술'),
      const RecipeIngredient(name: '설탕', amount: 1, unit: '작은술'),
      const RecipeIngredient(name: '소금', amount: 0.5, unit: '작은술'),
      const RecipeIngredient(name: '파슬리', amount: 1, unit: '줌', importance: IngredientImportance.optional),
    ],
    steps: [
      const RecipeStep(
        order: 1,
        description: '당근은 껍질을 벗기고 채칼이나 칼로 가늘게 채 썰어 주세요.',
        tip: '채칼을 사용하면 훨씬 빨리 할 수 있어요.',
      ),
      const RecipeStep(
        order: 2,
        description: '채 썬 당근에 소금을 뿌리고 10분간 절여 물기를 꼭 짜 주세요.',
        duration: Duration(minutes: 10),
      ),
      const RecipeStep(
        order: 3,
        description: '볼에 식초, 올리브유, 설탕을 섞어 드레싱을 만들어 주세요.',
      ),
      const RecipeStep(
        order: 4,
        description: '당근에 드레싱을 버무려 냉장고에 30분 이상 숙성시켜 주세요.',
        tip: '숙성할수록 더 맛있어요. 하룻밤 재워두면 최고예요.',
        duration: Duration(minutes: 30),
      ),
    ],
    nutrition: const Nutrition(
      calories: 95,
      carbs: 8,
      protein: 1,
      fat: 6,
    ),
  ),
  Recipe(
    id: 'r4',
    title: '돼지고기 간장 볶음',
    description: '달콤 짭짤한 간장 소스가 밥도둑! 쉽고 빠른 메인 반찬',
    difficulty: 2,
    cookingTimeMinutes: 15,
    servings: 2,
    emoji: '🥘',
    category: '한식',
    tags: ['돼지고기', '볶음', '밥도둑'],
    matchRate: 0.82,
    hasUrgentIngredient: true,
    ingredients: [
      const RecipeIngredient(name: '돼지고기 앞다리살', amount: 300, unit: 'g'),
      const RecipeIngredient(name: '양파', amount: 1, unit: '개'),
      const RecipeIngredient(name: '대파', amount: 1, unit: '대'),
      const RecipeIngredient(name: '간장', amount: 3, unit: '큰술'),
      const RecipeIngredient(name: '설탕', amount: 1, unit: '큰술'),
      const RecipeIngredient(name: '참기름', amount: 1, unit: '작은술'),
      const RecipeIngredient(name: '다진 마늘', amount: 1, unit: '큰술'),
    ],
    steps: [
      const RecipeStep(
        order: 1,
        description: '돼지고기는 먹기 좋은 크기로 썰고, 양파는 채 썰어 주세요.',
      ),
      const RecipeStep(
        order: 2,
        description: '간장 3큰술, 설탕 1큰술, 다진 마늘을 섞어 소스를 만들어 주세요.',
      ),
      const RecipeStep(
        order: 3,
        description: '달군 팬에 고기를 넣고 앞뒤로 노릇하게 구워 주세요.',
        duration: Duration(minutes: 4),
      ),
      const RecipeStep(
        order: 4,
        description: '양파를 넣고 투명해질 때까지 볶다가 소스를 넣어 조려 주세요.',
        duration: Duration(minutes: 5),
      ),
      const RecipeStep(
        order: 5,
        description: '불을 끄고 대파와 참기름을 넣어 마무리해 주세요.',
      ),
    ],
    nutrition: const Nutrition(
      calories: 380,
      carbs: 15,
      protein: 28,
      fat: 22,
    ),
  ),
];

/// 계란볶음밥(r1) 전용 학습카드 — Firestore 미설정 시 fallback
final mockLearnCards = [
  const LearnCard(
    id: 'lc1',
    type: CardType.intro,
    title: '계란볶음밥, 이 재료면 충분해요',
    emoji: '🍳',
    content:
        '오늘 배울 요리는 계란볶음밥이에요!\n\n필요한 재료는 단 5가지:\n🍚 찬밥 1공기 — 볶음밥의 핵심\n🥚 달걀 2개 — 고소함 담당\n🧅 대파 0.5대 — 향과 식감\n🫙 간장 1큰술 — 감칠맛\n🫙 참기름 0.5큰술 — 마무리 향\n\n당근을 더하면 색감과 영양까지 챙길 수 있어요.',
  ),
  const LearnCard(
    id: 'lc2',
    type: CardType.technique,
    title: '핵심 기술 ① 왜 찬밥일까?',
    emoji: '🍚',
    content:
        '계란볶음밥의 성패는 밥에 달렸어요.\n\n갓 지은 따뜻한 밥은 수분이 많아 볶을 때 뭉치고 질척해져요.\n\n반면 식은 찬밥은 밥알 표면이 살짝 마르고 단단해서 기름을 머금으며 고슬고슬하게 볶여요.\n\n💡 찬밥이 없다면? 갓 지은 밥을 넓은 접시에 펼쳐 5분만 식히세요.',
  ),
  const LearnCard(
    id: 'lc3',
    type: CardType.technique,
    title: '핵심 기술 ② 강불에서 빠르게',
    emoji: '🔥',
    content:
        '볶음밥은 "속도전"이에요.\n\n팬을 충분히 달군 뒤 강불을 유지하세요. 강불에서 빠르게 볶아야:\n\n✅ 밥알이 팬에 들러붙지 않고\n✅ 수분이 빠르게 날아가 고슬고슬해지며\n✅ 불맛(웍헤이)이 살아나요\n\n밥을 넣은 뒤엔 주걱으로 누르지 말고 뒤집듯이 볶아 주세요.',
  ),
  const LearnCard(
    id: 'lc4',
    type: CardType.quiz,
    title: '퀴즈: 고슬고슬 볶음밥의 비결은?',
    emoji: '❓',
    content: '계란볶음밥을 고슬고슬하게 만드는 가장 중요한 비결은 무엇일까요?',
    quizOptions: [
      QuizOption(text: '찬밥(식은 밥)을 사용한다', isCorrect: true),
      QuizOption(text: '약불에서 천천히 볶는다', isCorrect: false),
      QuizOption(text: '물을 조금 넣어 촉촉하게 한다', isCorrect: false),
      QuizOption(text: '뚜껑을 덮고 뜸을 들인다', isCorrect: false),
    ],
  ),
  const LearnCard(
    id: 'lc5',
    type: CardType.tip,
    title: '마무리 팁: 간장과 참기름 타이밍',
    emoji: '🧂',
    content:
        '같은 재료라도 넣는 순서가 맛을 바꿔요.\n\n🫙 간장은 밥을 볶을 때 팬 가장자리에 둘러 넣으세요. 뜨거운 팬에 닿아 살짝 타면서 불향과 감칠맛이 확 살아나요.\n\n🫙 참기름은 반드시 불을 끈 뒤 넣으세요. 가열하면 고소한 향이 날아가 버려요.\n\n이 두 가지만 지켜도 가게 볶음밥 맛이 나요! 👨‍🍳',
  ),
];
