// File generated by FlutterFire CLI (manually created from config files)
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPJ1jqtLk6NdChwJhytwRA-m0-M18TwaE',
    appId: '1:212536285784:web:6cdc11bda79ea7233e482d',
    messagingSenderId: '212536285784',
    projectId: 'hankki-plz',
    storageBucket: 'hankki-plz.firebasestorage.app',
    authDomain: 'hankki-plz.firebaseapp.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAodAc5WH8k4r_QWxTLeUC-p_5HC-Fgjw4',
    appId: '1:212536285784:android:3e93f1a8d76abb0a3e482d',
    messagingSenderId: '212536285784',
    projectId: 'hankki-plz',
    storageBucket: 'hankki-plz.firebasestorage.app',
    androidClientId: '212536285784-k10ipd0ga9o6sp5rg19ke5143mr27gb3.apps.googleusercontent.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPJ1jqtLk6NdChwJhytwRA-m0-M18TwaE',
    appId: '1:212536285784:ios:7ce335686ee5fdc43e482d',
    messagingSenderId: '212536285784',
    projectId: 'hankki-plz',
    storageBucket: 'hankki-plz.firebasestorage.app',
    iosClientId: '212536285784-plm2qu98g5iepbi4fo7lcof35l01d55b.apps.googleusercontent.com',
    iosBundleId: 'com.gdg.yorini.yorini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPJ1jqtLk6NdChwJhytwRA-m0-M18TwaE',
    appId: '1:212536285784:ios:7ce335686ee5fdc43e482d',
    messagingSenderId: '212536285784',
    projectId: 'hankki-plz',
    storageBucket: 'hankki-plz.firebasestorage.app',
    iosClientId: '212536285784-plm2qu98g5iepbi4fo7lcof35l01d55b.apps.googleusercontent.com',
    iosBundleId: 'com.gdg.yorini.yorini',
  );
}
